modLoader="javafml"
loaderVersion="[43,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="kitchen"
version="0.0.1"
displayName="kitchen"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="innatexlong, MCreator"
description='''
A mod of kitchen
'''

[[dependencies.kitchen]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




[[dependencies.kitchen]]
    modId="enderfood"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
